collections:
  - name: community.general
  - name: community.docker
  - name: ansible.posix
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: monolithprojects.github_actions_runner
    version: "1.25.1"
    src: https://github.com/MonolithProjects/ansible-github_actions_runner
