- name: Pull and run Netdata container
  community.docker.docker_container:
    name: netdata
    pull: always
    image: netdata/netdata:latest
    restart_policy: unless-stopped
    ports:
      - "{{ netdata_port }}:19999/tcp"
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor:unconfined
    env:
      NETDATA_CLAIM_TOKEN: "{{ netdata_claim_token }}"
    hostname: "${{ netdata_hostname }}"
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
