- name: Add Docker apt public key - seems to only be required for Ubuntu installations
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8
  when: ansible_distribution == "Ubuntu"

- name: Run geerlingguy.pip role to install Docker pip package
  ansible.builtin.include_role:
    name: geerlingguy.pip

- name: Run geerlingguy.docker role to install and configure Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: add_to_docker_group_result

- name: Reset SSH connection if Docker group membership changed
  ansible.builtin.meta: reset_connection
  when: add_to_docker_group_result.changed

- name: Create cron job to prune Docker objects
  ansible.builtin.cron:
    name: "Run Docker system prune"
    special_time: daily
    job: "docker system prune -af"

- name: Move Docker data root (if a specific data root is defined)
  when: docker_data_root != '/var/lib/docker'
  block:
    - name: Ensure Docker config directory exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Ensure defined Docker data root directory exists
      ansible.builtin.file:
        path: "{{ docker_data_root }}"
        state: directory
        mode: "0755"

    - name: Set data-root in daemon.json
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "data-root": "{{ docker_data_root }}",
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        mode: "0644"

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
