- name: Configure packages
  ansible.builtin.include_tasks: packages.yml

- name: Configure Python
  ansible.builtin.include_tasks: python.yml

- name: Configure Docker
  ansible.builtin.include_tasks: docker.yml

- name: Apply CVE mitigations
  ansible.builtin.include_tasks: cve_mitigations.yml