- name: Pull and run Blackfire container
  community.docker.docker_container:
    name: blackfire
    pull: always
    state: started
    image: blackfire/blackfire:2
    restart_policy: always
    ports:
      - "8307:8307/tcp"
    env:
      BLACKFIRE_CLIENT_ID="{{ blackfire_client_id }}"
      BLACKFIRE_CLIENT_TOKEN="{{ blackfire_client_token }}"
      BLACKFIRE_SERVER_ID="{{ blackfire_server_id }}"
      BLACKFIRE_SERVER_TOKEN="{{ blackfire_server_token }}"
      BLACKFIRE_LOG_LEVEL=4